spring:
  application:
    name: rsf-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/rsf_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 70MB
      max-request-size: 70MB
      enabled: true
      location: ${java.io.tmpdir}

server:
  port: 8081

logging:
  level:
    org.springframework.security: TRACE
    com.rsf.security: TRACE
    com.rsf.controller: DEBUG
    org.springframework.web.multipart: TRACE
    
jwt:
  secret: x4OY5Nq6FtY7Pz9QhCsDdFgHiJkLmNoPqRsTuVwXyZ0123456789   # 64-char random
  expiration-ms: 3600000

file:
  storage-path: ./file-storage  

task:
  execution:
    pool:
      core-size: 4
      max-size: 8